"""index for email

Revision ID: 1657ffaebc87
Revises: 2e5e5cfb0013
Create Date: 2026-06-02 13:25:43.922715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1657ffaebc87"
down_revision: Union[str, Sequence[str], None] = "2e5e5cfb0013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_address_Integer"), table_name="address")
    op.create_index(
        op.f("ix_address_employee_id"), "address", ["employee_id"], unique=False
    )
    op.alter_column(
        "employees",
        "role",
        existing_type=postgresql.ENUM(
            "UI", "UX", "Developer", "HR", name="employeerole"
        ),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(op.f("employees_email_key"), "employees", type_="unique")
    op.create_index(
        "uq_employee_email_active",
        "employees",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_employee_email_active", table_name="employees")
    op.create_unique_constraint(
        op.f("employees_email_key"),
        "employees",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "employees",
        "role",
        existing_type=postgresql.ENUM(
            "UI", "UX", "Developer", "HR", name="employeerole"
        ),
        server_default=sa.text("'Developer'::employeerole"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_address_employee_id"), table_name="address")
    op.create_index(
        op.f("ix_address_Integer"), "address", ["employee_id"], unique=False
    )
    # ### end Alembic commands ###
