"""postal_code(int to str) in Address

Revision ID: 1f3f02988930
Revises: b67702549be7
Create Date: 2026-06-01 00:44:58.554780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f3f02988930"
down_revision: Union[str, Sequence[str], None] = "b67702549be7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "address",
        "postal_code",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "address",
        "postal_code",
        existing_type=sa.String(length=100),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
