"""employee: add role column role

Revision ID: 2e5e5cfb0013
Revises: 50208300475c
Create Date: 2026-06-01 17:46:01.939776

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e5e5cfb0013"
down_revision: Union[str, Sequence[str], None] = "50208300475c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("address", "Integer", new_column_name="employee_id")

    # ### end Alembic commands ###


def downgrade():
    op.alter_column("address", "employee_id", new_column_name="Integer")
    # ### end Alembic commands ###
