"""add assciations

Revision ID: 4b37483b4f47
Revises: 1f3f02988930
Create Date: 2026-06-01 09:09:17.477837

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "4b37483b4f47"
down_revision: Union[str, Sequence[str], None] = "1f3f02988930"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
