"""employee: add role column role

Revision ID: 50208300475c
Revises: e1ba9acc6f10
Create Date: 2026-06-01 14:25:04.901303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50208300475c"
down_revision: Union[str, Sequence[str], None] = "e1ba9acc6f10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ROLE_ENUM = sa.Enum("UI", "UX", "Developer", "HR", name="employeerole")


def upgrade() -> None:
    """Upgrade schema."""

    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column("role", _ROLE_ENUM, server_default="Developer", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "role")
    # ### end Alembic commands ###
