"""add_password to Employee

Revision ID: b67702549be7
Revises: e9ae891a96a2
Create Date: 2026-05-29 16:02:38.642639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67702549be7'
down_revision: Union[str, Sequence[str], None] = 'e9ae891a96a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password_hash', sa.String(length=255), nullable=True))

    op.execute("UPDATE employees SET password_hash = 'placeholder' WHERE password_hash is NULL")

    op.alter_column("employees", "password_hash", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password_hash')
    # ### end Alembic commands ###
