"""employee: add column status

Revision ID: bc5e4f95cf81
Revises: 1657ffaebc87
Create Date: 2026-06-10 15:36:54.886584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc5e4f95cf81"
down_revision: Union[str, Sequence[str], None] = "1657ffaebc87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_STATUS_ENUM = sa.Enum("Active", "Inactive", "Probation", name="employeestatus")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###

    _STATUS_ENUM.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column("status", _STATUS_ENUM, server_default="Active", nullable=False),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "status")
    # ### end Alembic commands ###
