"""add columnn experience in employee

Revision ID: dd61de65ecda
Revises: bc5e4f95cf81
Create Date: 2026-06-10 16:37:25.829441

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "dd61de65ecda"
down_revision: Union[str, Sequence[str], None] = "bc5e4f95cf81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column("experience", sa.Integer(), server_default=0, nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("employees", "experience")
    # ### end Alembic commands ###
