"""department

Revision ID: e9ae891a96a2
Revises: 2aa5212fa7ab
Create Date: 2026-05-29 05:50:59.144332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ae891a96a2'
down_revision: Union[str, Sequence[str], None] = '2aa5212fa7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.add_column('address', sa.Column('Integer', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_address_employee_id'), table_name='address')
    op.create_index(op.f('ix_address_Integer'), 'address', ['Integer'], unique=False)
    op.drop_constraint(op.f('address_employee_id_fkey'), 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'employees', ['Integer'], ['id'], ondelete='CASCADE')
    op.drop_column('address', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key(op.f('address_employee_id_fkey'), 'address', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_address_Integer'), table_name='address')
    op.create_index(op.f('ix_address_employee_id'), 'address', ['employee_id'], unique=False)
    op.drop_column('address', 'Integer')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
